# Site settings
title: Yue's Homepage
email: yxz772 At case [dot] edu
description: Yue 's Ideas & Blogs
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
encoding: utf-8
exclude: [deprecated, vendor, Gemfile, Procfile]
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: peterz1991
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/peterz1991/peterz1991.github.io/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/peterz1991/peterz1991.github.io/
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: peterz1991
disqus_url: "http://peterz1991.github.io"
#########################################

# Build settings
markdown: kramdown

kramdown:
  input: GFM
# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
